language: cpp
os: linux

env:
  global:
    - secure: "cilRyAZJVGiS6jeAEG+An9fnOFb22HJKhyTlnHpAWonEwYvJ92s8NDWIU+oGp3Ch3J/UuAyuf3c9Y7sXPUeoJlT8vhA7GXbd9VFX/6yWaTzUhO6ybht8wOI/iPANcPMw8rfv4kPWA2REcip0bhCcJSWgaojgGTjcCyhfdweC5SQ="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

  coverity_scan:
    project:
      name: hluk/CopyQ

    notification_email: ruling.worlds@gmail.com

    build_command_prepend: cov-configure --template --comptype gcc --compiler gcc-4.8 && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-4.8 .
    build_command: make

    branch_pattern: coverity_scan

cache:
    apt: true
    ccache: true
    directories:
    - $HOME/.wheelhouse

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - utils/travis/before-install-${TRAVIS_OS_NAME}.sh

install:
  - utils/travis/install-${TRAVIS_OS_NAME}.sh

script:
  -

after_success:
  -

