os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc

cache:
    apt: true

before_install:
  - utils/travis-before-install-${TRAVIS_OS_NAME}.sh

install:
  - utils/travis-install-deps-${TRAVIS_OS_NAME}.sh

script:
  - utils/build-${TRAVIS_OS_NAME}.sh

after_success:
  - utils/after_build-${TRAVIS_OS_NAME}.sh
