language: cpp
compiler:
  - gcc
  - clang

install:
  - sudo apt-get update
  - sudo apt-get install libqt4-dev libxtst-dev openbox

before_install:
  - sudo pip install cpp-coveralls --use-mirrors

script:
  - qmake CONFIG+=debug QMAKE_CXXFLAGS+="--coverage" QMAKE_LFLAGS+="--coverage"
  - make
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - openbox &
  - ./copyq tests

after_success:
  - coveralls -e qxt -e src/platform -e src/tests -e /usr -e plugins/itemfakevim/fakevim -E '.*/moc_.*'
