# Configuration file for AppVeyor CI
configuration: Release

environment:
  VCINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\

  matrix:
    - QTDIR: C:\Qt\5.7\mingw53_32
      CMAKE_GENERATOR: MinGW Makefiles
      MINGW_PATH: C:\Qt\Tools\mingw530_32

    - QTDIR: C:\Qt\5.7\msvc2015
      CMAKE_GENERATOR: Visual Studio 14 2015
      VC_VARS_ARCH: x86

    - QTDIR: C:\Qt\5.7\msvc2015_64
      CMAKE_GENERATOR: Visual Studio 14 2015 Win64
      VC_VARS_ARCH: amd64

install:
- set PATH=%QTDIR%\bin;%PATH%
- set CMAKE_PREFIX_PATH=%QTDIR%\lib\cmake
# Note: Following also removes sh.exe from PATH so that CMake can generate MinGW Makefile.
- if NOT [%MINGW_PATH%] == [] set PATH=%MINGW_PATH%\bin;%PATH:C:\Program Files\Git\usr\bin;=%
- if [%VC_VARS_ARCH%] == [] call "%VCINSTALLDIR%\vcvarsall.bat" %VC_VARS_ARCH%

before_build:
- utils\appveyor-before-build.bat

build:

build_script:
- cmake --build build/ --config Release

after_build:
- utils\appveyor-after-build.bat

artifacts:
- path: 'copyq*.zip'
  name: CopyQ Portable

- path: 'copyq-*-setup.exe'
  name: CopyQ Setup

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
